### ISSUE TITLE
Chapter 0: Introduction

### ISSUE THREAD

**Issue by AndrewRathbun** [Digital-Forensics-Discord-Server/TheHitchhikersGuidetoDFIRExperiencesFromBeginnersandExperts#1]
Even though I am assigning this to myself, I welcome all input from the community.

 - [x] Purpose of this book
 - [x] Setting expectations for what the book is meant to be
 - [x] How this book came to be

**Comment by mcvic1rj** [comment]
I would suggest that there is a foreword or a section of the intro chapter on why the DFIR Community is important to the DFIR Community. Depending on the length/scope, this might even warrant its own chapter. 

#### Some initial thoughts on key points would be:
- Knowledge through the "Hive Mind"
  - Being able to pick peoples brains is important when struggling with a case. Not every department or organization is large enough to have multiple people be in forensics let alone be experts
  - Being able to share ideas on new projects (such as this one!)
- Community products are at the heart and soul of many commercial products. Being a part of the overall opensource community lets people focus or "fix" one small piece of the greater puzzle, and benefit many people (think photorec)
- Being able to influence how some vendors shape their products. My single license to product X is not much voice, but if I find others with the same problem in the community, we can ask for changes collectively

**Comment by AndrewRathbun** [comment]
> I would suggest that there is a foreword or a section of the intro chapter on why the DFIR Community is important to the DFIR Community. Depending on the length/scope, this might even warrant its own chapter.
> 
> #### Some initial thoughts on key points would be:
> * Knowledge through the "Hive Mind"
>   
>   * Being able to pick peoples brains is important when struggling with a case. Not every department or organization is large enough to have multiple people be in forensics let alone be experts
>   * Being able to share ideas on new projects (such as this one!)
> * Community products are at the heart and soul of many commercial products. Being a part of the overall opensource community lets people focus or "fix" one small piece of the greater puzzle, and benefit many people (think photorec)
> * Being able to influence how some vendors shape their products. My single license to product X is not much voice, but if I find others with the same problem in the community, we can ask for changes collectively

All great suggestions! I'm all for addressing these. Good call on the Foreword too. I'm not a writer by trade but if you want to help guide us with that vision, I'd be down. That's what this project is all about. Yeah, there are co-authors writing their respective chapters, but the community can really suggest edits and ideas like the above. It should be fun to watch this process play out.

**Comment by AndrewRathbun** [comment]
FYI I'm finishing up a research paper in the next week or so and then I'll be full steam on this chapter and Chapter 1.

**Comment by AndrewRathbun** [comment]
Note to self: include snip from Google Forms for the results of the 2 rounds of voting.

**Comment by AndrewRathbun** [comment]
Substantial completion of this chapter has been achieved!

**Comment by AndrewRathbun** [comment]
Need to add a section for the book cover voting process probably after this line

https://github.com/Digital-Forensics-Discord-Server/TheHitchhikersGuidetoDFIRExperiencesFromBeginnersandExperts/blob/16b5f27ca3e6b60fc0aff3878c8e376f47da4dce/manuscript/introduction.txt#L63
