### ISSUE TITLE
Cover of Book

### ISSUE THREAD

**Issue by AndrewRathbun** [Digital-Forensics-Discord-Server/TheHitchhikersGuidetoDFIRExperiencesFromBeginnersandExperts#12]
All discussion about what kind of graphic should go on the cover should occur here.

**Comment by AndrewRathbun** [comment]
Something else to consider:

![image](https://user-images.githubusercontent.com/36825567/167623470-22915361-70c9-42db-b3ee-3f7b85af0e85.png)

**Comment by Nisarg12** [comment]
Just a thought, but the cover is a fill-to-bound front of a hard disk with it's actuator arm, and the chapter covers can have platters illustrated with the title written on one of the tracks, and the arm slightly moves each chapter like it's accessing data. If leanpub does backcovers we can have the case of the hard disk with the SCSI connectors and other pins.

**Comment by gh0x0st** [comment]
still a good looking placeholder

**Comment by AndrewRathbun** [comment]
This is done!

![image](https://user-images.githubusercontent.com/36825567/184517212-70cb0486-e6e5-4ce9-939d-883e86ba02c1.png)

**Comment by AndrewRathbun** [comment]
Revised version of BookCover.jpg uploaded: https://github.com/Digital-Forensics-Discord-Server/TheHitchhikersGuidetoDFIRExperiencesFromBeginnersandExperts/commit/358d5f95e131da4802df41aa2137164db8089672
