### ISSUE TITLE
Chapter 5: Deobfuscating PowerShell Scripts/Payloads

### ISSUE THREAD

**Issue by AndrewRathbun** [Digital-Forensics-Discord-Server/TheHitchhikersGuidetoDFIRExperiencesFromBeginnersandExperts#15]

**Comment by AndrewRathbun** [comment]
@gh0x0st can you update this issue with your topic of choice? As interest grows, I want to make sure topics aren't duplicates for new people coming in.

**Comment by ApexPredator-InfoSec** [comment]
I'm pretty sure he was going to do deobfuscating powershell scripts/payloads.

**Comment by AndrewRathbun** [comment]
Hey there! I'm tentatively setting 7/31/2022 as a [milestone](https://github.com/Digital-Forensics-Discord-Server/CrowdsourcedDFIRBook/milestone/1) for publishing v1.0 of this book. We'll have the title decided in the next couple weeks which will be the first of [multiple administrative tasks](https://github.com/Digital-Forensics-Discord-Server/CrowdsourcedDFIRBook/milestone/2) we'll complete in July. At this point, **_please let me know_** if you intend to have at least a working, editable version of your chapter by 7/31/2022.

If not, please know that's perfectly fine. It doesn't mean your chapter won't get published, it just won't get published in v1.0. It'll simply be added when it's ready to be published and I'll push out a new version of the book, (i.e., V1.3, v1.7, etc) with your new content. I hope we have about 10 ready to go by 7/31/2022 so we can push to publish v1.0 shortly thereafter, but I won't know that until I hear from you! So, please let me know!

**Comment by ApexPredator-InfoSec** [comment]
When I talked to him last week he said he had content done and wanted to edit\clean it up before uploading. I'll ping him again and let him know he can going ahead an upload so you and the rest of the crew can help with the editing.

**Comment by gh0x0st** [comment]
I have uploaded the initial draft of the content for chapter 8. Thank you all again for being patient and understanding with me. Without everyone out of the hospital things are starting to get back to normal.

**Comment by AndrewRathbun** [comment]
> I have uploaded the initial draft of the content for chapter 8. Thank you all again for being patient and understanding with me. Without everyone out of the hospital things are starting to get back to normal.

Family first. ALWAYS. Hope things are on the mend for you very soon. 

I will mark your chapter as writing finished and editing needed. Thank you for your efforts!

**Comment by AndrewRathbun** [comment]
@gh0x0st I've done a pass through your chapter. Great stuff! Thank you for doing this chapter :)

**Comment by AndrewRathbun** [comment]
I need to figure out why your 2 images aren't parsing properly in the PDF, but it won't happen tonight. I'm exhausted...will tackle it tomorrow.

**Comment by gh0x0st** [comment]
Thank you for taking the time to go through it! This was a very fun topic. I made a typo in the markdown that I fixed after you generated the PDF so it may be all set. Is there anything  I need to do in the repo or leanpub? Also, I have a habit of critiquing myself after something is submitted so I may make a few minor formatting changes if that's ok.

**Comment by AndrewRathbun** [comment]
As we approach publishing v1 of this book, please review the most recent files uploaded to [this folder](https://github.com/Digital-Forensics-Discord-Server/TheHitchhikersGuidetoDFIRExperiencesFromBeginnersandExperts/tree/main/ExamplePublishedBook) and ensure your chapter looks the way you want it to. If not, please make appropriate adjustments and advise me to regenerate the preview book files. 

Additionally, if you've not been invited to the book on Leanpub yet, please provide me with an email address so I can invite you on there. 

Thank you for completing your chapter! I hope this has been a fulfilling experience for you!

**Comment by gh0x0st** [comment]
I gave it another read through and will sleep on it. Will comment again tomorrow after one more review.

**Comment by AndrewRathbun** [comment]
> I need to figure out why your 2 images aren't parsing properly in the PDF, but it won't happen tonight. I'm exhausted...will tackle it tomorrow.

Special thanks to @Nisarg12 for fixing this!

https://github.com/Digital-Forensics-Discord-Server/TheHitchhikersGuidetoDFIRExperiencesFromBeginnersandExperts/commit/315b55986969a9f3043df7b188b15ba8fd3474af

**Comment by gh0x0st** [comment]
I'm good to go .
