### ISSUE TITLE
Book Disclaimer idea

### ISSUE THREAD

**Issue by AndrewRathbun** [Digital-Forensics-Discord-Server/TheHitchhikersGuidetoDFIRExperiencesFromBeginnersandExperts#159]
@FullTang passed this on to me that he saw in another book. Maybe we could modify this and stick it somewhere, if we so choose?

```
“Every effort has been made in the preparation of this book to ensure the accuracy of the information presented. However, the information contained in this book is sold without warranty, either express or implied. Neither the author, nor Packt Publishing or its dealers and distributors, will be held liable for any damages caused or alleged to have been caused directly or indirectly by this book.”
```

Thoughts? Any feedback is appreciated. If we deem it not much of a value add, then we can simply scrap the idea.

**Comment by stark4n6** [comment]
I like the idea of it

**Comment by Fierry137** [comment]
I think it's a good idea to add it.

**Comment by AndrewRathbun** [comment]
https://github.com/Digital-Forensics-Discord-Server/TheHitchhikersGuidetoDFIRExperiencesFromBeginnersandExperts/blob/main/manuscript/Book.txt

Does everyone agree with the disclaimer positioning?

https://github.com/Digital-Forensics-Discord-Server/TheHitchhikersGuidetoDFIRExperiencesFromBeginnersandExperts/commit/24ffc0fc3efe1ff28a9d4c517b6edb333fe35aec

Here's the disclaimer I put together based on the above template. Any thoughts or suggestions? Feel free to PR if needed.

**Comment by FullTang** [comment]
Looks good to me.
