### ISSUE TITLE
Chapter 6: Gamification of DFIR - Playing CTF's

### ISSUE THREAD

**Issue by AndrewRathbun** [Digital-Forensics-Discord-Server/TheHitchhikersGuidetoDFIRExperiencesFromBeginnersandExperts#16]

**Comment by AndrewRathbun** [comment]
@stark4n6 List of tools is looking great. I think adding hyperlinks to each one (if possible) would add some nice value. Thoughts on that? If you're good with it, we'll wanna move EZ Tools to a separate line from KAPE, IMO.

**Comment by AndrewRathbun** [comment]
Putting this here so I don't forget, we'll want to remove the space before Hindsight here:

https://github.com/Digital-Forensics-Discord-Server/CrowdsourcedDFIRBook/blob/23e406d0048e59168e1fb28f7dcc7129e220c624/manuscript/chapter9.md?plain=1#L111

**Comment by AndrewRathbun** [comment]
Lastly, I made some changes to the previously bolded headers that weren't rendering properly. I converted them to Markdown headers using `##` because otherwise they were showing up on the same line as the first sentence of the paragraph they were supposed to be over. A solution to that would've been just adding another row below your `**text goes here**` but also might as well just use Markdown headers, I suppose. If you want any indented more so, just modify the appropriate number of `#` for the respective header and we should be good there.

**Comment by stark4n6** [comment]
Sounds good, I can get those hyperlinks added in the next round of updates/edits. Thanks for the syntax fixes as I've used a few different markdown sites with mixed results.

**Comment by AndrewRathbun** [comment]
![image](https://user-images.githubusercontent.com/36825567/166465688-81cb6838-5184-44dd-96f2-a271f2e976bc.png)

FYI looks like you've bolded the subheading for `What is a CTF?`. Just showing you that it appears to render as bolded in the Table of Contents, as well. Up to you if you want to keep that since its your chapter.

**Comment by stark4n6** [comment]
Definitely not intended, odd

**Comment by stark4n6** [comment]
Should be fixed now as well as the .txt is updated with tool paths and the latest changes

**Comment by Nisarg12** [comment]
Excellent chapter @stark4n6!

Since you've already covered CTFs very aptly, I have a suggestion that you include a topic for write-ups, explaining how they are important not only to practice documentation (which is a must skill for people in DFIR), but also giving back to the community. Or if you'd like I could write the section for you :)

Maybe you could include it under `Toss a Coin in the Tip Jar` and make `Tips for playing` it's own section with `Prior` & `During` as subsections.

**Comment by stark4n6** [comment]
The chapter is still a work in progress but thanks for the suggestions. I definitely want to add the writeups to the "For Profit" section.

**Comment by AndrewRathbun** [comment]
Hey there! I'm tentatively setting 7/31/2022 as a [milestone](https://github.com/Digital-Forensics-Discord-Server/CrowdsourcedDFIRBook/milestone/1) for publishing v1.0 of this book. We'll have the title decided in the next couple weeks which will be the first of [multiple administrative tasks](https://github.com/Digital-Forensics-Discord-Server/CrowdsourcedDFIRBook/milestone/2) we'll complete in July. At this point, **_please let me know_** if you intend to have at least a working, editable version of your chapter by 7/31/2022.

If not, please know that's perfectly fine. It doesn't mean your chapter won't get published, it just won't get published in v1.0. It'll simply be added when it's ready to be published and I'll push out a new version of the book, (i.e., V1.3, v1.7, etc) with your new content. I hope we have about 10 ready to go by 7/31/2022 so we can push to publish v1.0 shortly thereafter, but I won't know that until I hear from you! So, please let me know!

**Comment by stark4n6** [comment]
I should be done by the end of this week or next. I will let you know when review is needed.

**Comment by AndrewRathbun** [comment]
Dead Link Checker is hitting on the DFRWS link here: https://github.com/Digital-Forensics-Discord-Server/TheHitchhikersGuidetoDFIRExperiencesFromBeginnersandExperts/blob/2b63a20b992bb57f0e5381469860aaf58d97e393/manuscript/chapter9.txt#L52

Just passing along. No action needed as it may correct itself, but just a heads up, sir.

**Comment by AndrewRathbun** [comment]
If you've not already, please consider filling out your bio here before the end of the month: https://github.com/Digital-Forensics-Discord-Server/TheHitchhikersGuidetoDFIRExperiencesFromBeginnersandExperts/blob/main/manuscript/authors.txt

**Comment by AndrewRathbun** [comment]
@stark4n6 I've added my edits: https://github.com/Digital-Forensics-Discord-Server/TheHitchhikersGuidetoDFIRExperiencesFromBeginnersandExperts/commit/18831d93c817f9cda0bb61325c52cc83759d68bd

Feel free to adjust as necessary. Great work!

**Comment by AndrewRathbun** [comment]
As we approach publishing v1 of this book, please review the most recent files uploaded to [this folder](https://github.com/Digital-Forensics-Discord-Server/TheHitchhikersGuidetoDFIRExperiencesFromBeginnersandExperts/tree/main/ExamplePublishedBook) and ensure your chapter looks the way you want it to. If not, please make appropriate adjustments and advise me to regenerate the preview book files. 

Additionally, if you've not been invited to the book on Leanpub yet, please provide me with an email address so I can invite you on there. 

Thank you for completing your chapter! I hope this has been a fulfilling experience for you!
