### ISSUE TITLE
Chapter 12: Data Recovery (mark-b1980)

### ISSUE THREAD

**Issue by AndrewRathbun** [Digital-Forensics-Discord-Server/TheHitchhikersGuidetoDFIRExperiencesFromBeginnersandExperts#175]
https://github.com/Digital-Forensics-Discord-Server/TheHitchhikersGuidetoDFIRExperiencesFromBeginnersandExperts/blob/main/manuscript/chapterL.txt

Here you go, enjoy!

**Comment by AndrewRathbun** [comment]
@mark-b1980 I am working through a review of the chapter right now. We should probably decide on one of either instable or unstable. Thoughts? I see instances of both but it would probably make sense to choose one since they mean the same thing. Thoughts?

**Comment by AndrewRathbun** [comment]
I'm about 1/3rd of the way through reviewing this chapter. So far so good. I will continue reviewing it throughout the weekend. Nice work!

**Comment by mark-b1980** [comment]
Hi. Thanks for the feedback - go with **unstable** please. it's more common used when describing that problems.

**Comment by AndrewRathbun** [comment]
FYI, there are a few `xxxxxx` for the captions on some images. Did you mean to replace those eventually?

**Comment by AndrewRathbun** [comment]
@mark-b1980 outside of that issue, I did my first runthrough of the chapter and pushed the edits. Let me know if there's anything you disagree with, etc. Once you address the image captions, we can push a new version. Cheers!

**Comment by mark-b1980** [comment]
I have created another pull request with the 4 missing image captions. I looked over the changes you have dont and all is OK. Please pull the last changes and then go ahed... Have a nice sunday.

**Comment by AndrewRathbun** [comment]
Chapter published!
