### ISSUE TITLE
Low resolution images 

### ISSUE THREAD

**Issue by AndrewRathbun** [Digital-Forensics-Discord-Server/TheHitchhikersGuidetoDFIRExperiencesFromBeginnersandExperts#186]
Feedback from a reader:

"The images in Chapter 2, Pages between 29 to 35 and pages 56 to 59 are the ones."

**Comment by ApexPredator-InfoSec** [comment]
I didn't have any good tools for scaling down the images to fit on the page. I'll try to relook it mid-June after I have a little free time again.

**Comment by ApexPredator-InfoSec** [comment]
High resolution images uploaded. Looks good in book preview. Awaiting second look for QA/QC before publishing.
