### ISSUE TITLE
Chapter 13: Methodology for Parsing Unsupported Artifacts

### ISSUE THREAD

**Issue by B1N2H3X** [Digital-Forensics-Discord-Server/TheHitchhikersGuidetoDFIRExperiencesFromBeginnersandExperts#22]
Write a chapter providing a methodology to attack unsupported artifacts.  The process to be described covers the following topics:
- Introduction to the methodology
- Discover
- Test 
- Find
- Parse
- Share

**Comment by AndrewRathbun** [comment]
Will this be generalized? Mobile? Computer?

**Comment by B1N2H3X** [comment]
@AndrewRathbun - this is focused on unsupported artifacts. While we may use mobile examples, the methodology is more broadly applicable. 
Can I bring a coauthor in?  Elizabeth McPherson.  
This is the methodology I teach at the university - so would love to document it here in the book while simultaneously codifying it in another format for folks to learn from and I am working on that with Elizabeth.

Thanks!

**Comment by AndrewRathbun** [comment]
@B1N2H3X yeah of course you can. She'll just need a GitHub account to contribute to this repo and a Leanpub account eventually. You can send her my way on Discord if she needs any more direction but the magic will happen here in this repo.

**Comment by AndrewRathbun** [comment]
Hey there! I'm tentatively setting 7/31/2022 as a [milestone](https://github.com/Digital-Forensics-Discord-Server/CrowdsourcedDFIRBook/milestone/1) for publishing v1.0 of this book. We'll have the title decided in the next couple weeks which will be the first of [multiple administrative tasks](https://github.com/Digital-Forensics-Discord-Server/CrowdsourcedDFIRBook/milestone/2) we'll complete in July. At this point, **_please let me know_** if you intend to have at least a working, editable version of your chapter by 7/31/2022.

If not, please know that's perfectly fine. It doesn't mean your chapter won't get published, it just won't get published in v1.0. It'll simply be added when it's ready to be published and I'll push out a new version of the book, (i.e., V1.3, v1.7, etc) with your new content. I hope we have about 10 ready to go by 7/31/2022 so we can push to publish v1.0 shortly thereafter, but I won't know that until I hear from you! So, please let me know!

**Comment by AndrewRathbun** [comment]
This chapter will no longer be published at the author's request.
