### ISSUE TITLE
Chapter 3: Password Cracking for Beginners

### ISSUE THREAD

**Issue by AndrewRathbun** [Digital-Forensics-Discord-Server/TheHitchhikersGuidetoDFIRExperiencesFromBeginnersandExperts#7]

**Comment by FullTang** [comment]
My chapter would be an eye-opener into how password cracking works so that more data can be obtained from encrypted devices and show why using strong passwords and not reusing passwords is a good idea. In digital forensics, the first challenge is to actually get the data in a state so that it can be analyzed. I feel that I have a solid understanding of how to use Hashcat and how to build custom word lists to crack some of the more stubborn passwords. It wouldn't be a super high-level analysis of password cracking, this would be at a level for the examiner who knows what the command line is but may have never used a CLI tool before.

**Comment by AndrewRathbun** [comment]
Sounds awesome. Really looking forward to it!

**Comment by FullTang** [comment]
A slight change to the chapter title, but the same basic concept.

**Comment by AndrewRathbun** [comment]
Hey there! I'm tentatively setting 7/31/2022 as a [milestone](https://github.com/Digital-Forensics-Discord-Server/CrowdsourcedDFIRBook/milestone/1) for publishing v1.0 of this book. We'll have the title decided in the next couple weeks which will be the first of [multiple administrative tasks](https://github.com/Digital-Forensics-Discord-Server/CrowdsourcedDFIRBook/milestone/2) we'll complete in July. At this point, **_please let me know_** if you intend to have at least a working, editable version of your chapter by 7/31/2022.

If not, please know that's perfectly fine. It doesn't mean your chapter won't get published, it just won't get published in v1.0. It'll simply be added when it's ready to be published and I'll push out a new version of the book, (i.e., V1.3, v1.7, etc) with your new content. I hope we have about 10 ready to go by 7/31/2022 so we can push to publish v1.0 shortly thereafter, but I won't know that until I hear from you! So, please let me know!

**Comment by AndrewRathbun** [comment]
pasting the above like I am in all topics for posterity.

@FullTang do you consider this chapter done and ready for editing?

**Comment by AndrewRathbun** [comment]
I made it to line 60 tonight. I have to call it a night. I've uploaded some minor edits so check them out when you get a chance. I will continue review this weekend!

**Comment by AndrewRathbun** [comment]
@FullTang great work on this one! I've finished my review pass and pushed the changes. I'll generate new preview files now and upload them.

**Comment by AndrewRathbun** [comment]
@FullTang as I mentioned on Discord, you may want to take another pass through and `code block` more things in the chapter. I made some of those changes but I'll leave it to you to flesh out the rest based on author's preference.

**Comment by AndrewRathbun** [comment]
If you've not already, please consider filling out your bio here before the end of the month: https://github.com/Digital-Forensics-Discord-Server/TheHitchhikersGuidetoDFIRExperiencesFromBeginnersandExperts/blob/main/manuscript/authors.txt

**Comment by AndrewRathbun** [comment]
As we approach publishing v1 of this book, please review the most recent files uploaded to [this folder](https://github.com/Digital-Forensics-Discord-Server/TheHitchhikersGuidetoDFIRExperiencesFromBeginnersandExperts/tree/main/ExamplePublishedBook) and ensure your chapter looks the way you want it to. If not, please make appropriate adjustments and advise me to regenerate the preview book files. 

Additionally, if you've not been invited to the book on Leanpub yet, please provide me with an email address so I can invite you on there. 

Thank you for completing your chapter! I hope this has been a fulfilling experience for you!
