### ISSUE TITLE
Chapter 9: Imaging

### ISSUE THREAD

**Issue by AndrewRathbun** [Digital-Forensics-Discord-Server/TheHitchhikersGuidetoDFIRExperiencesFromBeginnersandExperts#79]
Fierry137

**Comment by AndrewRathbun** [comment]
@Fierry137 will this cover imaging computers, mobile, other, all the above, etc? Just trying to figure out which section this chapter might fall into.

**Comment by Fierry137** [comment]
It's probably going to be limited to computers and RAM memory. I think mobile imaging might fit better in one of the mobile chapters due to the various limitations (OS, manufacturer, lock bypassing and physical/logical imaging differences)

**Comment by AndrewRathbun** [comment]
@Fierry137 can you make a `chapter17.txt` file which is what Leanpub parses to generate the chapter?

**Comment by Fierry137** [comment]
Sure, I can create it in the coming days (currently on holiday abroad without laptop) and instantly merge any feedback that is generated when the editing is completed.

**Comment by AndrewRathbun** [comment]
If you've not already, please consider filling out your bio here before the end of the month: https://github.com/Digital-Forensics-Discord-Server/TheHitchhikersGuidetoDFIRExperiencesFromBeginnersandExperts/blob/main/manuscript/authors.txt

**Comment by AndrewRathbun** [comment]
As we approach publishing v1 of this book, please review the most recent files uploaded to [this folder](https://github.com/Digital-Forensics-Discord-Server/TheHitchhikersGuidetoDFIRExperiencesFromBeginnersandExperts/tree/main/ExamplePublishedBook) and ensure your chapter looks the way you want it to. If not, please make appropriate adjustments and advise me to regenerate the preview book files. 

Additionally, if you've not been invited to the book on Leanpub yet, please provide me with an email address so I can invite you on there. 

Thank you for completing your chapter! I hope this has been a fulfilling experience for you!

**Comment by Fierry137** [comment]
> @Fierry137 I added my edits: [27b98f9](https://github.com/Digital-Forensics-Discord-Server/TheHitchhikersGuidetoDFIRExperiencesFromBeginnersandExperts/commit/27b98f95e79943ec793577ae32124c7edfcd1f36)
> 
> It seemed like the chapter ended abruptly? It was good stuff but just wondering if you were done or needed to add a conclusion still? Please advise when you can!

I think a conclusion is in order, I’ll add it in the coming days :)

**Comment by Fierry137** [comment]
A conclusion and some next steps have been added :)

**Comment by AndrewRathbun** [comment]
> A conclusion and some next steps have been added :)

I just finished reviewing this, check out the edits! Let me know if you have any feedback! Cheers and thank you for finishing your chapter. Will get you added to the ISBN here shortly.
