### ISSUE TITLE
Chapter 10: Linux

### ISSUE THREAD

**Issue by AndrewRathbun** [Digital-Forensics-Discord-Server/TheHitchhikersGuidetoDFIRExperiencesFromBeginnersandExperts#83]
bgrundy (LinuxLEO)'s chapter

**Comment by AndrewRathbun** [comment]
Hey there! I'm tentatively setting 7/31/2022 as a [milestone](https://github.com/Digital-Forensics-Discord-Server/CrowdsourcedDFIRBook/milestone/1) for publishing v1.0 of this book. We'll have the title decided in the next couple weeks which will be the first of [multiple administrative tasks](https://github.com/Digital-Forensics-Discord-Server/CrowdsourcedDFIRBook/milestone/2) we'll complete in July. At this point, **_please let me know_** if you intend to have at least a working, editable version of your chapter by 7/31/2022.

If not, please know that's perfectly fine. It doesn't mean your chapter won't get published, it just won't get published in v1.0. It'll simply be added when it's ready to be published and I'll push out a new version of the book, (i.e., V1.3, v1.7, etc) with your new content. I hope we have about 10 ready to go by 7/31/2022 so we can push to publish v1.0 shortly thereafter, but I won't know that until I hear from you! So, please let me know!

**Comment by bgrundy** [comment]
I should have something fleshed out by the end of this week.   7/31 is plenty of time.

**Comment by bgrundy** [comment]
I'm hoping to have a draft up by Friday or Saturday evening for peer review/editing.

**Comment by AndrewRathbun** [comment]
I'll add this to book.txt later unless someone beats me to it.

**Comment by AndrewRathbun** [comment]
> I'll add this to book.txt later unless someone beats me to it.

https://github.com/Digital-Forensics-Discord-Server/TheHitchhikersGuidetoDFIRExperiencesFromBeginnersandExperts/commit/2f3c55b1d49061123bf0dda5e026ff1c0b0bc065

I was able to quick add it. Will review it later. Thank you for getting it done :)

**Comment by AndrewRathbun** [comment]
https://github.com/Digital-Forensics-Discord-Server/TheHitchhikersGuidetoDFIRExperiencesFromBeginnersandExperts/commit/c0107bd66a4d06cb4d41fbfe6157ba7901deefa0

Preview files were just added with your chapter included, FYI.

**Comment by AndrewRathbun** [comment]
I think some of the preformatted sections have to be modified for Leanpub. They don't appear to be parsing correctly.

**Comment by AndrewRathbun** [comment]
I will likely review this chapter tomorrow. Thanks for your work @bgrundy

**Comment by bgrundy** [comment]
Roger that.  Any changes I make will likely be formatting.  I still don't like some of the code blocks (with text formatting).  I need to do that after work today.

**Comment by AndrewRathbun** [comment]
Editing completed! Nice work on this one!


https://github.com/Digital-Forensics-Discord-Server/TheHitchhikersGuidetoDFIRExperiencesFromBeginnersandExperts/commit/5370c33e9fc2602e19ddee72d45c14a71e6f84c6 and https://github.com/Digital-Forensics-Discord-Server/TheHitchhikersGuidetoDFIRExperiencesFromBeginnersandExperts/commit/21489dace0ee1f2168d234999bf5360eb17bec63
